#ifndef COMPUTER_INFO_QR_QRCODE_H_
#define COMPUTER_INFO_QR_QRCODE_H_

#include <Uefi.h>

#define COMPUTER_INFO_QR_MIN_VERSION                  7
#define COMPUTER_INFO_QR_MAX_VERSION                  23
#define COMPUTER_INFO_QR_MAX_SIZE                     (4 * COMPUTER_INFO_QR_MAX_VERSION + 17)
#define COMPUTER_INFO_QR_MAX_PAYLOAD_LENGTH           1094
#define COMPUTER_INFO_QR_MAX_ERROR_CORRECTION_BLOCKS  9
#define COMPUTER_INFO_QR_MAX_ECC_CODEWORDS_PER_BLOCK  30
#define COMPUTER_INFO_QR_MAX_TOTAL_CODEWORDS          \
  (COMPUTER_INFO_QR_MAX_PAYLOAD_LENGTH + \
   (COMPUTER_INFO_QR_MAX_ERROR_CORRECTION_BLOCKS * COMPUTER_INFO_QR_MAX_ECC_CODEWORDS_PER_BLOCK))

typedef struct {
  UINTN Size;
  UINT8 Modules[COMPUTER_INFO_QR_MAX_SIZE][COMPUTER_INFO_QR_MAX_SIZE];
} COMPUTER_INFO_QR_CODE;

EFI_STATUS
GenerateComputerInfoQrCode(
  IN  CONST UINT8              *Payload,
  IN  UINTN                    PayloadLength,
  OUT COMPUTER_INFO_QR_CODE    *QrCode
  );

#endif
